apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: sonarqube
  name: sonarqube
spec:
  tags:
  - annotations:
      description: Provides a SonarQube Continuous Inspection Service on CentOS 7.
      openshift.io/display-name: SonarQube (Latest)
      tags: hidden,instant-app,sonarqube
    from:
      kind: ImageStreamTag
      name: "7.0"
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      description: Provides a SonarQube 7.0 Continuous Inspection Service on CentOS 7.
      openshift.io/display-name: SonarQube 7.0
      tags: hidden,instant-app,sonarqube
      version: "7.0"
    from:
      kind: DockerImage
      name: "docker.io/griso78/sonarqube:7.0"
    name: "7.0"
    referencePolicy:
      type: Local  
